### ISSUE TITLE
How to log error messages?

### ISSUE THREAD

**Issue by phstc** [roidrage/lograge#130]
I'm experimenting lograge with logstash formatter and it's working well for info logs, formatting them using JSON-logstash properly, but if the application raises an exception, it logs the error without formatting it as a JSON. Consequently mixing the log file with JSON and normal (text) logs.

Is there a way to force lograge to also format error logs?

**Comment by pxlpnk** [comment]
Hey @phstc depending on what kind of error messages you want to log there different approaches. As lograge just takes care of the request logging it will not be able yet to log errors throw within the controller, however you can catch them yourself. Log them and throw them again so that your application behaves like it should.

Error messages should be in general handled within an error tracker and not in logs.

**Comment by phstc** [comment]
Hey @pxlpnk thanks! I like your idea :beers: I will send the request logs to Logstash (using lograge) and keep the error logs only in our error tracker.
