### ISSUE TITLE
Failing to log JSON with UTF-8 chars

### ISSUE THREAD

**Issue by ealders** [roidrage/lograge#210]
Getting the following error in Rails 4.2.8 with lograge v0.3.6 with the Logstash formatter:
  Could not log "process_action.action_controller" event. Encoding::UndefinedConversionError: "\\xEF" from ASCII-8BIT to UTF-8.

Seems UTF-8 character encodings in the URL are causing problems for the JSON encoder included with Rails. Is there a way to safely filter these or change the encoding before passing them to be converted to JSON?

**Comment by benlovell** [comment]
The stdlib JSON parser has a bit of trouble with characters it considers outside of the usual ASCII range. You could potentially try and force encoding in the logstash formatter as a workaround. I see logstash itself relies on OJ's parser which I believe is somewhat more permissive.

I'd be open to a PR that alters our logstash formatter to use the `LogStash::Json.dump` instead, if you can verify this correctly dumps your given string - otherwise please include a failing spec I can use to repro and dig further.

**Comment by springerigor** [comment]
One possible workaround is to force encoding as mentioned by @benlovell. 

`logstash` gem has `Charset` utility which supports it (https://github.com/elastic/logstash/blob/ceb5103e01564cba0fb26314f22cebd3ed393cb0/logstash-core/lib/logstash/util/charset.rb).

Steps to reproduce the problem:

```ruby
[7] pry(main)> text = [0xEB].pack("C*")
=> "\xEB"
[8] pry(main)> text.encoding
=> #<Encoding:ASCII-8BIT>
[9] pry(main)> text.to_json
Encoding::UndefinedConversionError: "\xEB" from ASCII-8BIT to UTF-8
from /Users/igorspringer/.rvm/gems/ruby-2.3.3/gems/activesupport-4.2.8/lib/active_support/core_ext/object/json.rb:34:in `encode'
```

**Comment by onebree** [comment]
Any updates on how to implement this workaround when initializing Lograge in a project? I've encountered this issue (just with a different `\x` character) and have been trying to look for a solution for a couple days now. I considered even updating Logstash (`logstash-event`), but the gem's version is maxed out and seems to be deprecated now.

**Comment by chase439** [comment]
We're on lograge 0.10.0 and getting same error. Any more details on a workaround?

**Comment by chase439** [comment]
Since this problem only happens to me on file upload, https://github.com/roidrage/lograge/issues/92 was very helpful.

**Comment by tmedford** [comment]
We are on 0.11.2 and getting issue.
